// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Rocket Ship":return img`
..............................
..............................
..............................
..............................
............ffff..............
...........f2222f.............
..........f222222f............
.........fe2222222f...........
.........fe2222222f...........
.........fe2222222f...........
.......fffe2ffff22fff.........
......f1dfefd111f2fd1f........
......f1dfefd111f2fd1f........
......f1dfefddd1f2fd1f........
......f1dfeeffff22fd1f........
......f1dfeeeeee22fd1f........
......fdffe2222222ffdf........
......fdffe2222222ffdf........
......ffefe2ffff22feff........
......f2efefd111f2fe2f........
.....f22efefd111f2fe22f.......
....f222efefddd1f2fe222f......
...f2eeeefeeffff22feee22f.....
...fffffffeeeeee22fffffff.....
......fddfee222222fddf........
......f1dfee222222fd1f........
......f1dfeeeee222fd1f........
.......fffeeeeeee2fff.........
.........ffffffffff...........
..........f445544f............
..........f244442f............
..........f2244222............
...........f2442f.............
...........22222f.............
............f22f..............
.............f2...............
..............................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
